version: "3.4"

services:
 wallet-logging:
 container_name: wallet-logging
 image: ${IMAGE_NAME}
 ports:
 - "4002:4002"
 env_file:
 - .env
 depends_on:
 - db

 db:
 image: postgres:latest
 volumes:
 - ./docker/volumes/postgres-data:/postgres/postgres-data:z
 ports:
 - ${wallet_logging_db_port}:5432
 healthcheck:
 test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
 timeout: 45s
 interval: 10s
 retries: 10
 restart: always
 env_file:
 .env







